'use client';
import {useState,useEffect,useMemo,useRef} from 'react';
import {ArrowRight,Search,MapPin,Heart,BedDouble,UtensilsCrossed,Plane,Compass,CalendarDays,BriefcaseBusiness,Globe2,ChevronRight,ArrowUpRight,Plus,Check,SlidersHorizontal,Wine,Landmark,Ship,Trash2,Download,Scale,LoaderCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty} from '@/components/ui/empty';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Hotel,TripItem,cities,photos,findHotels,safeUrl,validDates,flightUrl} from '@/lib/catalog';
function Picker({value,onChange,options,label,className=''}:{value:string;onChange:(v:string)=>void;options:string[];label:string;className?:string}){return <Select value={value} onValueChange={v=>v&&onChange(String(v))}><SelectTrigger aria-label={label} className={className}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select>}
function HotelImage({hotel,className=''}:{hotel:Hotel;className?:string}){const [failed,setFailed]=useState(false);return photos[hotel.id]&&!failed?<img className={className} src={photos[hotel.id]} alt={hotel.name} loading="lazy" onError={()=>setFailed(true)}/>:<div className={'placeholderphoto '+className}><span>{hotel.city}<span style={{display:'block',fontFamily:'-apple-system,sans-serif',fontSize:12,marginTop:7,opacity:.75}}>Hotel photography coming soon</span></span></div>}
export default function Page(){
const [hotels,setHotels]=useState<Hotel[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
const [view,setView]=useState('discover'),[tab,setTab]=useState('hotels'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[city,setCity]=useState('All destinations'),[sort,setSort]=useState('Featured stays'),[limit,setLimit]=useState(12);
const [selected,setSelected]=useState<Hotel|null>(null),[saved,setSaved]=useState<string[]>([]),[trip,setTrip]=useState<TripItem[]>([]),[compared,setCompared]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[account,setAccount]=useState(false),[toast,setToast]=useState('');
const [start,setStart]=useState('2026-10-14'),[end,setEnd]=useState('2026-10-18'),[guests,setGuests]=useState(2),[today,setToday]=useState('2026-09-05');
const [from,setFrom]=useState('New York'),[to,setTo]=useState('Paris'),[cabin,setCabin]=useState('Business'),[journey,setJourney]=useState('Round trip'),[flightError,setFlightError]=useState(''),[flightReady,setFlightReady]=useState(false),[flightLink,setFlightLink]=useState('');
const [cuisine,setCuisine]=useState('All cuisines');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const hotelRef=useRef(hotels);hotelRef.current=hotels;
function notify(message:string){setToast(message);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),3200)}
async function load(){setLoading(true);setError('');try{const response=await fetch('/data/hotels.json');if(!response.ok)throw new Error();setHotels(await response.json())}catch{setError('We couldn’t load the hotel collection. Please try again.')}finally{setLoading(false)}}
useEffect(()=>{void load();const localToday=new Date();const date=[localToday.getFullYear(),String(localToday.getMonth()+1).padStart(2,'0'),String(localToday.getDate()).padStart(2,'0')].join('-');setToday(date);if(date>'2026-10-14'){const later=new Date(localToday);later.setDate(later.getDate()+7);setStart(later.toISOString().slice(0,10));later.setDate(later.getDate()+4);setEnd(later.toISOString().slice(0,10))}try{const a=JSON.parse(localStorage.getItem('aurum-saved')||'[]'),b=JSON.parse(localStorage.getItem('aurum-trip')||'[]');if(Array.isArray(a))setSaved(a.filter(x=>typeof x==='string'));if(Array.isArray(b))setTrip(b.filter(x=>x&&typeof x.id==='string'&&typeof x.date==='string'&&typeof x.name==='string'))}catch{notify('Device storage is unavailable. You can still explore and plan this session.')}return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
useEffect(()=>{setLimit(12)},[search,city,sort,cuisine,view,tab]);
useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(mc.registerTool({name:'search_hotel_catalog',description:'Search the imported hotel and dining catalog by city, hotel, or cuisine. Read-only; does not book.',inputSchema:{type:'object',properties:{query:{type:'string'},city:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const i=input as {query?:unknown;city?:unknown};if(!i||typeof i.query!=='string'||(i.city!==undefined&&(typeof i.city!=='string'||!cities.includes(i.city))))throw new Error('Provide a text query and an optional supported city.');if(!hotelRef.current.length)throw new Error('Catalog is still loading.');return findHotels(hotelRef.current,i.query,typeof i.city==='string'?i.city:'All destinations','Featured stays').slice(0,20).map(h=>({id:h.id,name:h.name,city:h.city,diningOptions:h.venues.length,website:h.website}))}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
function saveHotel(id:string){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);try{localStorage.setItem('aurum-saved',JSON.stringify(next));notify(next.includes(id)?'Added to your saved places':'Removed from saved places')}catch{notify('Saved for this session; device storage is unavailable.')}}
function updateTrip(next:TripItem[]){setTrip(next);try{localStorage.setItem('aurum-trip',JSON.stringify(next));return true}catch{notify('Updated for this session; device storage is unavailable.');return false}}
function addTrip(item:Omit<TripItem,'date'|'endDate'|'guests'>){if(!validDates(start,end,today)){notify('Choose a future check-in and a later check-out first.');return}const exists=trip.some(t=>t.id===item.id&&t.date===start);if(exists){notify('Already in your itinerary for these dates');return}if(updateTrip([...trip,{...item,date:start,endDate:end,guests}]))notify('Added to your draft itinerary · not a reservation')}
function nav(next:string){setView(next);setCompared([]);window.scrollTo({top:0,behavior:'smooth'})}
function explore(){if(!validDates(start,end,today)){notify('Choose a future check-in and a later check-out.');return}setSearch(query);if(!['hotels','dining'].includes(tab))setTab('hotels')}
const filtered=useMemo(()=>findHotels(hotels,search,city,sort).filter(h=>(view!=='saved'||saved.includes(h.id))&&(cuisine==='All cuisines'||h.venues.some(v=>v.cuisine.toLowerCase().includes(cuisine.toLowerCase())))),[hotels,search,city,sort,view,saved,cuisine]);
const initial=view==='discover'&&tab==='hotels'&&!search&&city==='All destinations'&&sort==='Featured stays';
const shortlist=hotels.filter(h=>compared.includes(h.id));
const activityCity=city==='All destinations'?'Paris':city;
const activities=[{name:'Taste the city',description:'Market walks, cooking classes, and wine tastings with local hosts.',term:'food wine tasting',icon:Wine},{name:'Culture, up close',description:'Private guides, extraordinary museums, and the stories behind the city.',term:'private cultural tour',icon:Landmark},{name:'A different perspective',description:'Scenic cruises and day trips that take you beyond the familiar.',term:'cruise day trip',icon:Ship}];
function reset(){setQuery('');setSearch('');setCity('All destinations');setCuisine('All cuisines');setSort('Featured stays')}
function exportTrip(){const text=['AURUM — MY DRAFT ITINERARY','Plans only. Confirm reservations with each provider.','',...trip.map(t=>`${t.date}${t.endDate?' – '+t.endDate:''} | ${t.name} | ${t.city} | ${t.guests} adults | ${t.type}`)].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='aurum-itinerary.txt';a.click();URL.revokeObjectURL(url)}
return <div className="shell"><header className="topbar"><a href="/" className="brand" aria-label="Aurum home"><span className="brandmark">A</span>AURUM</a><nav className="topnav" aria-label="Main navigation">{[['discover','Discover'],['saved','Saved places'],['trips','My trips']].map(([v,l])=><button key={v} onClick={()=>nav(v)} className={view===v?'active':''}>{l}{v==='saved'&&saved.length>0?<span className="count">{saved.length}</span>:null}</button>)}</nav><div className="profile"><button className="textbtn" onClick={()=>setAccount(true)} aria-label="About your travel workspace"><Globe2 size={17}/><span className="desktopword">EN</span></button><button className="avatar" onClick={()=>setAccount(true)} aria-label="Your workspace">A</button></div></header>
<main className="main"><div className="headingrow"><div><div className="eyebrow">{view==='trips'?'Make room for the memorable':view==='saved'?'Your personal collection':'The art of going somewhere'}</div><h1>{view==='trips'?'Your next chapter, planned.':view==='saved'?'Places you’re dreaming of.':'Where will your curiosity take you?'}</h1><p>{view==='trips'?'Bring your stays, tables, and experiences together.':view==='saved'?'A little inspiration today. An unforgettable journey tomorrow.':'Exceptional stays. Remarkable tables. All in one place.'}</p></div><span className="datebadge"><Compass size={16}/>A world worth discovering</span></div>
{view!=='trips'&&<><form className="searchbox" onSubmit={e=>{e.preventDefault();explore()}}><div className="searchfields"><div className="field destinationfield"><label htmlFor="where">Where to?</label><input id="where" value={query} onChange={e=>setQuery(e.target.value)} placeholder="City, hotel, or a cuisine you love"/></div><div className="field"><label htmlFor="checkin">Check-in</label><input id="checkin" type="date" value={start} min={today} required onChange={e=>{setStart(e.target.value);setFlightReady(false)}}/></div><div className="field"><label htmlFor="checkout">Check-out</label><input id="checkout" type="date" value={end} min={start} required onChange={e=>{setEnd(e.target.value);setFlightReady(false)}}/></div><div className="field guestfield"><label htmlFor="guests">Travelers</label><input id="guests" type="number" min="1" max="9" value={guests} onChange={e=>{setGuests(Math.max(1,Math.min(9,Number(e.target.value)||1)));setFlightReady(false)}} aria-label="Number of adults"/></div><button className="primary" type="submit"><Search size={17}/>Explore</button></div></form>
{view==='discover'&&<Tabs value={tab} onValueChange={v=>{setTab(String(v));setCuisine('All cuisines')}} className="category-tabs"><TabsList className="category-list" aria-label="Explore travel">{[{v:'hotels',l:'Hotels',I:BedDouble},{v:'dining',l:'Hotel dining',I:UtensilsCrossed},{v:'flights',l:'Flights',I:Plane},{v:'experiences',l:'Experiences',I:Compass}].map(({v,l,I})=><TabsTrigger key={v} value={v} className="category-tab"><I size={17}/>{l}</TabsTrigger>)}</TabsList></Tabs>}
{(tab!=='flights'||view==='saved')&&<div className="filterrow"><div className="chips">{['All destinations',...cities.slice(0,5)].map(c=><button key={c} onClick={()=>setCity(c)} className={'chip '+(city===c?'active':'')}>{c}</button>)}</div><Picker label="Choose from all 12 destinations" value={city} options={['All destinations',...cities]} onChange={setCity} className="viewtoggle"/></div>}</>}
{(view==='saved'||(view==='discover'&&['hotels','dining'].includes(tab)))&&<>
{initial&&<section className="feature"><img src="/images/bangkok.jpg" alt="Mandarin Oriental Bangkok beside the Chao Phraya River" fetchPriority="high"/><div className="featurebody"><span className="glass"><UtensilsCrossed size={12}/>The dining collection</span><h2>A great journey<br/>starts at the table.</h2><p>Discover extraordinary hotels with dining<br/>worth traveling for.</p><button className="secondary" onClick={()=>{setTab('dining');setSort('Most dining options')}}>Explore hotel dining<ArrowRight size={15}/></button></div><button className="feature-location" onClick={()=>setSelected(hotels.find(h=>h.id==='bkk-mandarin-oriental')||null)}><MapPin size={13}/>Mandarin Oriental, Bangkok<ArrowUpRight size={12}/></button></section>}
<div className="sectiontitle"><div><h2>{view==='saved'?'Your saved places':tab==='dining'?'Find your kind of table.':initial?'Stay for the experience.':city==='All destinations'?'The hotel collection':`Stays in ${city}`}</h2><p>{loading?'Opening the collection…':view==='saved'?`${filtered.length} saved places · stored on this device`:initial?'Distinctive hotels, with exceptional dining at their heart.':`${filtered.length.toLocaleString()} hotels${search?` matching “${search}”`:''} · ${filtered.reduce((n,h)=>n+h.venues.length,0).toLocaleString()} dining options`}</p></div>{initial?<button className="textbtn" onClick={()=>{setSort('Name A–Z')}}>Explore all stays<ArrowRight size={15}/></button>:<Picker value={sort} onChange={setSort} options={['Featured stays','Most dining options','Name A–Z']} label="Sort hotels" className="viewtoggle"/>}</div>
{tab==='dining'&&<div className="filterrow"><div className="chips">{['All cuisines','French','Japanese','Chinese','Italian','Thai','Indian'].map(c=><button key={c} className={'chip '+(cuisine===c?'active':'')} onClick={()=>setCuisine(c)}>{c}</button>)}</div><span className="small desktopword">Compare dining options, side by side</span></div>}
{error?<div className="dataerror" role="alert">{error}<button className="secondary" onClick={()=>void load()}>Try again</button></div>:loading?<Empty className="empty"><LoaderCircle className="animate-spin"/><p>Opening 1,513 hotels and their dining collections…</p></Empty>:!filtered.length?<Empty className="empty"><Heart size={30}/><h2>{view==='saved'&&!saved.length?'Your collection starts here':'No places found'}</h2><p>{view==='saved'&&!saved.length?'Tap the heart on a hotel to keep it close.':'Try another destination, hotel name, or cuisine.'}</p><button className="primary" onClick={()=>{reset();nav('discover');setTab('hotels')}}>Explore hotels<ArrowRight size={16}/></button></Empty>:<><div className="cards">{filtered.slice(0,initial&&limit===12?3:limit).map(h=><article className="hotelcard" key={h.id}><button className={'save '+(saved.includes(h.id)?'saved':'')} onClick={()=>saveHotel(h.id)} aria-label={(saved.includes(h.id)?'Unsave ':'Save ')+h.name} aria-pressed={saved.includes(h.id)}><Heart size={16} fill={saved.includes(h.id)?'currentColor':'none'}/></button><button className="cardimage" onClick={()=>setSelected(h)} aria-label={'Explore '+h.name}><HotelImage hotel={h}/><span className="cardtag">{photos[h.id]?'The dining collection':h.brand==='n/a'?'Hotel collection':h.brand}</span></button><div className="cardbody"><div className="cardcity">{h.city}, {h.country}<span className="stars">{Number.parseFloat(h.stars)===5?'★★★★★':`${h.stars==='n/a'?'':h.stars+' ★'}`}</span></div><h3><button onClick={()=>setSelected(h)}>{h.name}</button></h3><div className="location"><MapPin size={12}/>{h.district==='n/a'?h.city:h.district}</div><button className="diningline" onClick={()=>{setSelected(h)}}><UtensilsCrossed size={14}/>{h.venues.length} dining {h.venues.length===1?'option':'options'}<span className="diningsample"> · {h.venues[0]?.cuisine.split(',')[0]}</span><ChevronRight size={13}/></button><div className="cardfoot"><span><strong>{h.price.startsWith('$')?h.price:'Luxury stay'}</strong><span className="small"> · {h.price.startsWith('$')?'price band':'see hotel rates'}</span></span><button className="textbtn" onClick={()=>setSelected(h)}>Discover<ChevronRight size={14}/></button></div><label className="inlinecheck comparecheck"><Checkbox aria-label={'Compare '+h.name} checked={compared.includes(h.id)} onCheckedChange={checked=>{if(checked&&compared.length>=3){notify('Compare up to 3 hotels at a time');return}setCompared(checked?[...compared,h.id]:compared.filter(x=>x!==h.id))}}/>Compare dining</label></div></article>)}</div>{filtered.length>limit&&<div className="more"><button className="secondary" onClick={()=>setLimit(initial&&limit===12?24:limit+12)}>Show more stays<span className="small">{Math.min(initial&&limit===12?3:limit,filtered.length)} of {filtered.length.toLocaleString()}</span><Plus size={15}/></button></div>}</>}
</>}
{view==='discover'&&tab==='flights'&&<section className="flightbox"><div className="eyebrow">The journey is part of the experience</div><div className="sectiontitle"><div><h2>A better way to get there.</h2><p>Set your route. Compare current fares on Google Flights.</p></div><Plane size={34} strokeWidth={1.1}/></div><form onSubmit={e=>{e.preventDefault();setFlightError('');if(!from.trim()||!to.trim()||from.trim().toLowerCase()===to.trim().toLowerCase()){setFlightError('Choose different departure and arrival cities.');return}if(start<today||!start||(journey==='Round trip'&&!validDates(start,end,today))){setFlightError('Choose valid future travel dates.');return}setFlightLink(flightUrl(from,to,start,end,guests,cabin,journey==='One way'));setFlightReady(true)}}><div className="flightgrid"><label className="inputfield">From<input required value={from} onChange={e=>{setFrom(e.target.value);setFlightReady(false)}} placeholder="City or airport"/></label><label className="inputfield">To<input required value={to} onChange={e=>{setTo(e.target.value);setFlightReady(false)}} placeholder="City or airport"/></label><div className="inputfield"><span>Journey</span><Picker value={journey} onChange={v=>{setJourney(v);setFlightReady(false)}} options={['Round trip','One way']} label="Journey type"/></div><div className="inputfield"><span>Cabin</span><Picker value={cabin} onChange={v=>{setCabin(v);setFlightReady(false)}} options={['Economy','Premium economy','Business','First class']} label="Cabin class"/></div><label className="inputfield">Departure<input type="date" required min={today} value={start} onChange={e=>{setStart(e.target.value);setFlightReady(false)}}/></label>{journey==='Round trip'&&<label className="inputfield">Return<input type="date" required min={start} value={end} onChange={e=>{setEnd(e.target.value);setFlightReady(false)}}/></label>}</div><button className="primary" type="submit"><Search size={17}/>Find flights</button>{flightError&&<p role="alert" className="dataerror">{flightError}</p>}</form>{flightReady&&<div className="flightresult"><div><strong>{from} <ArrowRight size={16} style={{display:'inline'}}/> {to}</strong><p>{start}{journey==='Round trip'?` – ${end}`:''} · {cabin} · {guests} {guests===1?'adult':'adults'}</p></div><a className="primary" href={flightLink} target="_blank" rel="noopener noreferrer">Compare live fares<ArrowUpRight size={17}/></a></div>}<p className="notice">Fares, seat availability, baggage, and booking are handled by Google Flights and your selected airline. Review the search details there before booking.</p></section>}
{view==='discover'&&tab==='experiences'&&<><div className="sectiontitle"><div><h2>{activityCity}, beyond the hotel.</h2><p>Choose an experience to explore with local providers.</p></div><Compass size={28}/></div><div className="activitygrid">{activities.map(({name,description,term,icon:Icon})=><article className="activity" key={name}><div className="activityicon"><Icon size={25} strokeWidth={1.3}/></div><div className="eyebrow">{activityCity}</div><h3>{name}</h3><p>{description}</p><a className="secondary" href={'https://www.getyourguide.com/s/?q='+encodeURIComponent(activityCity+' '+term)} target="_blank" rel="noopener noreferrer">Explore experiences<ArrowUpRight size={16}/></a><button className="textbtn" style={{marginTop:18}} onClick={()=>addTrip({id:'experience-'+activityCity+'-'+name,name,city:activityCity,type:'experience'})}><Plus size={15}/>Add idea to itinerary</button></article>)}</div><p className="notice">Experience ideas, not confirmed departures. Current options, prices, and reservations are available on GetYourGuide.</p></>}
{view==='trips'&&<><div className="sectiontitle"><div><h2>Your draft itinerary</h2><p>{trip.length} {trip.length===1?'plan':'plans'} · saved on this device · reservations made separately</p></div>{trip.length>0&&<button className="secondary" onClick={exportTrip}><Download size={16}/>Export</button>}</div>{!trip.length?<Empty className="empty"><BriefcaseBusiness size={36} strokeWidth={1.2}/><h2>Every great trip starts with a place.</h2><p>Add a hotel, a memorable meal, or an experience to begin your itinerary.</p><button className="primary" onClick={()=>{nav('discover');setTab('hotels')}}>Find your first stay<ArrowRight size={16}/></button></Empty>:[...trip].sort((a,b)=>a.date.localeCompare(b.date)).map(item=><article className="triprow" key={item.id+item.date}>{item.type==='hotel'?<BedDouble size={22}/>:item.type==='dining'?<UtensilsCrossed size={22}/>:<Compass size={22}/>}<div className="grow"><div className="eyebrow" style={{fontSize:10,marginBottom:7}}>{item.date} · {item.type}</div><h3>{item.name}</h3><p>{item.city} · {item.guests} adults · planned</p></div>{item.hotelId&&<button className="secondary" onClick={()=>setSelected(hotels.find(h=>h.id===item.hotelId)||null)}>Details<ArrowUpRight size={14}/></button>}<button className="iconbtn" onClick={()=>updateTrip(trip.filter(t=>!(t.id===item.id&&t.date===item.date)))} aria-label={'Remove '+item.name}><Trash2 size={15}/></button></article>)}</>}
<footer className="footer"><span>AURUM<span style={{margin:'0 12px',opacity:.4}}>|</span>Travel well. Dine exceptionally.</span><button className="textbtn" style={{fontSize:12}} onClick={()=>setAccount(true)}>1,513 hotels · 12 cities · About the collection<ArrowUpRight size={12}/></button></footer></main>
<Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="detailpanel">{selected&&<><HotelImage hotel={selected} className="detailhero"/><div className="detailbody"><div className="eyebrow">{selected.city} · {selected.country}</div><SheetTitle style={{fontSize:29,margin:'10px 0'}}>{selected.name}</SheetTitle><SheetDescription>{selected.address}</SheetDescription><p>{selected.description}</p><div className="detailactions">{safeUrl(selected.website)?<a href={safeUrl(selected.website)} target="_blank" rel="noopener noreferrer" className="primary">Check availability<ArrowUpRight size={16}/></a>:<span className="notice">Booking website not listed in the source.</span>}<button className="secondary" onClick={()=>saveHotel(selected.id)}><Heart size={16} fill={saved.includes(selected.id)?'currentColor':'none'}/>{saved.includes(selected.id)?'Saved':'Save hotel'}</button></div><p className="small">Booking continues on the hotel’s official website. Confirm your dates, travelers, room rate, and cancellation terms there.</p><div className="stayplan"><CalendarDays size={17}/><div>{start} – {end}<span className="small" style={{display:'block'}}>{guests} adults · draft plan</span></div><button className="textbtn" onClick={()=>addTrip({id:'hotel-'+selected.id,name:selected.name,city:selected.city,type:'hotel',hotelId:selected.id})}><Plus size={16}/>Add to trip</button></div><div className="sectiontitle"><div><h2>At the table</h2><p>{selected.venues.length} restaurants, bars & other dining options</p></div><UtensilsCrossed size={24}/></div>{selected.venues.map((v,i)=><div className="venue" key={v.name+i}><h4>{v.name}</h4><div className="meta">{v.type} · {v.cuisine}{v.price!=='n/a'?' · '+v.price:''}</div><p>{v.description}</p><div style={{display:'flex',justifyContent:'space-between',gap:8}}><span className="small">{v.location!=='n/a'?v.location:''}</span><button className="textbtn" onClick={()=>addTrip({id:selected.id+'-venue-'+i,name:v.name,city:selected.city,type:'dining',hotelId:selected.id})}><Plus size={14}/>Add to trip</button></div></div>)}<div className="sectiontitle"><h2>Good to know</h2></div><p><strong>Price band:</strong> {selected.price}<br/><strong>Getting there:</strong> {selected.transit}<br/><strong>Neighborhood:</strong> {selected.neighborhood}</p><p className="small">Details are from the supplied hotel and dining collection. Venue openings, awards, and menus may change; check directly with the hotel.</p><div style={{display:'flex',gap:15,flexWrap:'wrap'}}>{selected.sources.filter(s=>safeUrl(s)).slice(0,3).map((s,i)=><a className="textbtn" key={i} href={safeUrl(s)} target="_blank" rel="noopener noreferrer">Source {i+1}<ArrowUpRight size={12}/></a>)}</div></div></>}</SheetContent></Sheet>
{compared.length>0&&!compareOpen&&<div className="comparebar"><span>{compared.length} of 3 hotels selected</span><button className="secondary" disabled={compared.length<2} onClick={()=>setCompareOpen(true)}><Scale size={16}/>Compare dining</button><button className="textbtn" style={{color:'white'}} onClick={()=>setCompared([])}>Clear</button></div>}
<Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent style={{maxWidth:1000,width:'94vw',maxHeight:'85vh',overflow:'auto',padding:28}}><DialogTitle style={{fontSize:25}}>A table for every taste.</DialogTitle><DialogDescription>Compare the dining collections. Venue counts describe variety, not a quality rating.</DialogDescription><div className="comparetable"><Table><TableHeader><TableRow><TableHead>Hotel</TableHead>{shortlist.map(h=><TableHead key={h.id}>{h.name}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell>Destination</TableCell>{shortlist.map(h=><TableCell key={h.id}>{h.city}</TableCell>)}</TableRow><TableRow><TableCell>Dining options</TableCell>{shortlist.map(h=><TableCell key={h.id}><strong>{h.venues.length}</strong></TableCell>)}</TableRow><TableRow><TableCell>Hotel price band</TableCell>{shortlist.map(h=><TableCell key={h.id}>{h.price}</TableCell>)}</TableRow><TableRow><TableCell>Restaurants & bars</TableCell>{shortlist.map(h=><TableCell key={h.id}>{h.venues.map((v,i)=><div style={{marginBottom:15}} key={i}><strong style={{fontWeight:500}}>{v.name}</strong><div className="small">{v.cuisine}</div></div>)}</TableCell>)}</TableRow><TableRow><TableCell>Explore</TableCell>{shortlist.map(h=><TableCell key={h.id}><button className="secondary" onClick={()=>{setCompareOpen(false);setSelected(h)}}>Hotel details<ArrowRight size={14}/></button></TableCell>)}</TableRow></TableBody></Table></div></DialogContent></Dialog>
<Dialog open={account} onOpenChange={setAccount}><DialogContent className="account" style={{maxWidth:470}}><DialogTitle style={{fontSize:25}}>Your Aurum workspace</DialogTitle><DialogDescription>Exceptional travel, thoughtfully collected.</DialogDescription><p>Explore 1,513 hotels and 5,755 dining entries across 12 cities, imported from your supplied collection.</p><p>Your saved places and draft itinerary live in this browser on this device. Plans are not reservations. Hotel, flight, and activity bookings are completed with external providers.</p><p className="small">Photography: Mandarin Oriental Bangkok via WBP Stars; The Peninsula Paris via Polycor; The Savoy via Architectural Digest India. Photographs belong to their respective owners.</p><button className="primary" onClick={()=>{setAccount(false);nav('saved')}}>Open saved places<Heart size={16}/></button></DialogContent></Dialog>
<nav className="mobilebar" aria-label="Mobile navigation">{[{v:'discover',l:'Discover',I:Compass},{v:'saved',l:'Saved',I:Heart},{v:'trips',l:'My trips',I:BriefcaseBusiness}].map(({v,l,I})=><button key={v} onClick={()=>nav(v)} className={view===v?'active':''}><I size={21} strokeWidth={1.6}/>{l}</button>)}<button onClick={()=>setAccount(true)}><Globe2 size={21} strokeWidth={1.6}/>Profile</button></nav>{toast&&<div role="status" className="toast">{toast}</div>}</div>
}
