"use client";
import { useEffect, useState } from "react";
import { ArrowDown, BedDouble, Camera, MapPin, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
const API = "https://bwrodcxmdzrpyrshrlfd.supabase.co/functions/v1/travel-api";
type Place = {id:string;name:string;city:string;category:string};
type Visit = {id:string;place:Place;visitedOn:string|null;overall:number;michelinStars:number;photos:{id:string}[]};
type Stay = {id:string;place:Place;checkIn:string;checkOut:string;rating:number|null};
type Recap = {title:string;destination:string;startDate:string|null;endDate:string|null;dateMode:string;hasMap:boolean;stops:{id:string;name:string;arrival:string;nights:number}[];places:Visit[];hotels:Stay[];stats:{nights:number;cities:number;flightMiles:number;rated:number;stars:number;average:number|null}};
type Day = {id:string;label:string;cities:string[];places:Visit[];stays:Stay[]};
const dateLabel = (s:string) => new Date(s+"T12:00:00Z").toLocaleDateString(undefined,{month:"short",day:"numeric",timeZone:"UTC"});
function daysFor(r:Recap):Day[] {
 const days=new Map<string,Day>();
 function add(key:string,city:string,label?:string) { if(!days.has(key)) days.set(key,{id:key,label:label??(key==="undated"?"Memories without a date":dateLabel(key)),cities:[],places:[],stays:[]});const d=days.get(key)!;if(city&&!d.cities.includes(city))d.cities.push(city);return d; }
 let offset=0;
 for(const stop of r.stops){for(let i=0;i<=stop.nights;i++){const date=new Date(stop.arrival+"T12:00:00Z");date.setUTCDate(date.getUTCDate()+i);const key=r.dateMode==="dates"?date.toISOString().slice(0,10):`day-${String(offset+i).padStart(3,"0")}`;add(key,stop.name,r.dateMode==="dates"?undefined:`Day ${offset+i+1}`);}offset+=stop.nights;}
 if(!days.size&&r.dateMode==="dates"&&r.startDate&&r.endDate){let d=new Date(r.startDate+"T12:00:00Z");for(let i=0;i<=365&&d.toISOString().slice(0,10)<=r.endDate;i++){add(d.toISOString().slice(0,10),r.destination);d.setUTCDate(d.getUTCDate()+1);}}
 for(const p of r.places)add(p.visitedOn||"undated",p.place.city).places.push(p);
 for(const h of r.hotels)add(h.checkIn,h.place.city).stays.push(h);
 return [...days.values()].sort((a,b)=>a.id.localeCompare(b.id));
}
export default function Home(){
 const [recap,setRecap]=useState<Recap|null>(null),[token,setToken]=useState(""),[state,setState]=useState("loading"),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();const key=location.hash.slice(1);if(!/^[a-f0-9]{80}$/.test(key)){setState("welcome");return;}setToken(key);setState("loading");fetch(`${API}/s/${key}?view=recap&format=json`,{signal:controller.signal,cache:"no-store",referrerPolicy:"no-referrer"}).then(async res=>{if(!res.ok)throw new Error(res.status===404?"unavailable":"network");const value=await res.json() as Recap;if(!value.stats||!Array.isArray(value.places))throw new Error("unavailable");setRecap(value);setState("ready");}).catch(e=>{if(e.name!=="AbortError")setState(e.message==="unavailable"?"unavailable":"error");});return()=>controller.abort();},[attempt]);
 const image=(id:string)=>`${API}/s/${token}?view=recap&asset=${encodeURIComponent(id)}`;
 if(!recap||state!=="ready")return <main className="welcome"><div className="wordmark">SEUR</div><p className="eyebrow">A trip to remember</p><h1>{state==="loading"?"Opening a little story…":state==="welcome"?"The places stay with you.":state==="unavailable"?"This story is no longer shared.":"We couldn’t load this recap."}</h1><p>{state==="welcome"?"Open a recap link shared by a friend to see their route, photos and favourite places.":state==="unavailable"?"The traveler may have revoked this link. Ask them for a new one.":state==="error"?"Check your connection, then try again.":"Gathering the route and memories."}</p>{state==="error"&&<Button onClick={()=>setAttempt(x=>x+1)}>Try again</Button>}</main>;
 const stats=[[recap.stats.nights,"Nights"],[recap.stats.cities,"City stops"],[recap.stats.flightMiles.toLocaleString(),"Flight miles¹"],[recap.stats.rated,"Places rated"],[recap.stats.stars,"Michelin stars"],[recap.stats.average?.toFixed(1)??"—","Average / 10"]];
 return <main className="recap"><header className="masthead"><a href="/" className="wordmark">SEUR</a><span>A trip, remembered</span></header><section className="intro"><p className="eyebrow">THE RECAP</p><h1>{recap.title}</h1><p className="route">{recap.stops.map(s=>s.name).join(" → ")||recap.destination}</p>{recap.startDate&&recap.endDate&&recap.dateMode==="dates"&&<p className="dates">{dateLabel(recap.startDate)} — {dateLabel(recap.endDate)} · {recap.startDate.slice(0,4)}</p>}<a href="#memories" className="jump">Relive the days <ArrowDown size={16}/></a></section>
 {recap.hasMap&&<figure className="route-map"><img src={image("map")} alt="The trip route with numbered city stops" referrerPolicy="no-referrer"/><figcaption><span>Gold · city route &nbsp; Teal · booked flights</span><a href="https://www.apple.com/legal/internet-services/maps/" rel="noreferrer">Apple Maps</a></figcaption></figure>}
 <section className="stats" aria-label="Trip highlights">{stats.map(([n,label])=><div key={String(label)}><strong>{n}</strong><span>{label}</span></div>)}</section><p className="footnote">¹ Great-circle distance for flights with known airport locations.</p>
 <section id="memories" className="memories"><div className="section-title"><p className="eyebrow">THE MOMENTS BETWEEN</p><h2>Day by day</h2></div>{daysFor(recap).map((d,i)=><article className="day" key={d.id}><div className="day-heading"><span className="day-index">{String(i+1).padStart(2,"0")}</span><div><h3>{d.label}</h3><p>{d.cities.join(" → ")}</p></div></div><div className="day-body">{d.stays.map(h=><div className="stay" key={h.id}><BedDouble size={20}/><div><span className="small-label">Stayed at</span><h4>{h.place.name}</h4><p>{dateLabel(h.checkIn)} — {dateLabel(h.checkOut)}</p></div>{h.rating!=null&&<span className="rating">{h.rating.toFixed(1)}<small>/10</small></span>}</div>)}{d.places.map(p=><div className="visit" key={p.id}><div className="visit-heading"><MapPin size={18}/><div><h4>{p.place.name}</h4><p>{p.place.category}{p.michelinStars>0?` · ${p.michelinStars} Michelin ${p.michelinStars===1?"star":"stars"}`:""}</p></div>{p.overall>0&&<span className="rating"><Star size={13}/>{p.overall.toFixed(1)}<small>/10</small></span>}</div>{p.photos.length>0&&<div className={`photos count-${p.photos.length}`}>{p.photos.map(photo=><a href={image(photo.id)} target="_blank" rel="noreferrer" aria-label={`Open photo of ${p.place.name}`} key={photo.id}><img loading="lazy" src={image(photo.id)} alt={`A memory from ${p.place.name}`} referrerPolicy="no-referrer"/></a>)}</div>}</div>)}{!d.places.length&&!d.stays.length&&<p className="empty-day"><Camera size={17}/>A day kept for the memories.</p>}</div></article>)}{!daysFor(recap).length&&<p className="empty-day">This traveler hasn’t added journal memories yet.</p>}</section><footer><span className="wordmark">SEUR</span><p>Well planned. Beautifully remembered.</p><small>Shared by the traveler · Personal ratings, not official reviews</small></footer></main>;
}
